# generated by a zon2nix fork (https://github.com/emneo-dev/zon2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "1220232ab38d0c2cfb10680115c17ad2fa1a8531dbaf8bbfb359ec67e80c7d5f5758";
    path = fetchzip {
      url = "https://github.com/karlseguin/metrics.zig/archive/8892dce43b46a69c8e736329629f38df232adee1.tar.gz";
      hash = "sha256-JN+s2VI6zKotfJ4sDbGrjSBz3JAVrcZk3npkXUNOMho=";
    };
  }
  {
    name = "12204ee130dbefc6f0de0c2b9e48f946ae8114f5f111256724122e17575a1ee7e2fb";
    path = fetchzip {
      url = "https://github.com/karlseguin/websocket.zig/archive/cf89cb8b9c61c99982ced19da54890983e226245.tar.gz";
      hash = "sha256-aLIMgRGV9sLs+M0+b8E9BRn5ftiqj3nbL9K/Fti+BeE=";
    };
  }
  {
    name = "12206f5d1e5bd4793fe952bbae891b7424a19026e0d296a1381074c7d21d5d76c1a1";
    path = fetchzip {
      url = "https://github.com/karlseguin/zul/archive/08c989bf6871e87807a4668232913ee245425863.tar.gz";
      hash = "sha256-jq0fQo22IfvhkpufIjN7mnhwe4/W9/3tHhtsh6AONBI=";
    };
  }
  {
    name = "12208c1f2c5f730c4c03aabeb0632ade7e21914af03e6510311b449458198d0835d6";
    path = fetchzip {
      url = "https://github.com/karlseguin/http.zig/archive/7d2ddae87af9b110783085c0ea6b03985faa4584.tar.gz";
      hash = "sha256-CGZXRtrS8G+FDaBCpDOqqHLGcfYT7m/BowTk0P3uEQo=";
    };
  }
  {
    name = "1220b0979ea9891fa4aeb85748fc42bc4b24039d9c99a4d65d893fb1c83e921efad8";
    path = fetchzip {
      url = "https://github.com/ziglibs/ini/archive/e18d36665905c1e7ba0c1ce3e8780076b33e3002.tar.gz";
      hash = "sha256-PmhXsK+mTmOrRC4u8cs9ol2XwKZv0HVRXpntaR5CJiw=";
    };
  }
  {
    name = "1220c032d828e768348b321a79523812be1c4cb27e1eb7ff5df54b573fa131afd448";
    path = fetchzip {
      url = "https://github.com/karlseguin/log.zig/archive/97d0818270a357d3ce7bc878abc32dc996fe78ff.tar.gz";
      hash = "sha256-ahqqywOKsSlucCPmmqaZjrayNgUXoQV3w4VazsKgkyI=";
    };
  }
]
