# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
  fetchgit,
}:
linkFarm "zig-packages" [
  {
    name = "clap-0.12.0-oBajB7foAQDqlSwaSG5g0yq7xGbQARUsBk5T64gAOqP5";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.12.0.tar.gz";
      hash = "sha256-HveL7aJBC+/8PNlGYxtNZBrk3ytkM8zuXENO9JpygC0=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9YnsrAAAxl1kQHi95ths2vSkdPIJxzUg6e2Oo83w_";
    path = fetchzip {
      url = "https://github.com/ziglibs/ini/archive/10cfba648f709588ab2f8785f56641024c510df9.tar.gz";
      hash = "sha256-+5aUqjTlr477Nrt0mdhPaDPH8s5T+UqPGeLGPhypPZs=";
    };
  }
  {
    name = "logz-0.0.0-O9YWXsllAgBq-S0z6q8AInWjei8h7polkVVRzJIGE-jW";
    path = fetchzip {
      url = "https://github.com/karlseguin/log.zig/archive/7fa8de39ad4d4adc54fce4d9bb0b6bc6c0076592.tar.gz";
      hash = "sha256-8v4jGPlIDLjjJbhdEF8wZJDdKmlwei7dI8MdBc+abvg=";
    };
  }
  {
    name = "metrics-0.0.0-W7G4eIegAQD4XxA9Co7Atbw59u_2zvxYf406AZuoAHPM";
    path = fetchzip {
      url = "https://github.com/karlseguin/metrics.zig/archive/6de29b83a750a06c438d268543e0e3c3c1b309da.tar.gz";
      hash = "sha256-F0tnpGmcPtNIff+i9z9ZVWttLvAKQNXQzVAKnsSFV+o=";
    };
  }
  {
    name = "zul-0.0.0-1oDot2KwBwC9c43wC7V9y4-xxg0a_d9okFDcJPhqmije";
    path = fetchzip {
      url = "https://github.com/karlseguin/zul/archive/146f9d5b2238c3a621b96345adf03490900c2fe2.tar.gz";
      hash = "sha256-vgjW3rXKzBM8z10FZiOwPY451eGHgaOSJri+qCAdU+Y=";
    };
  }
]
