when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, pull_request, manual, tag]

steps:
  build:
    image: alpine:3.24
    commands:
      - apk add --no-cache zig scdoc
      - time zig build -Dman_pages --summary all
      - time zig build -Dbuild_all -Doptimize=Debug --summary all
      - time zig build -Dbuild_all -Doptimize=ReleaseSafe --summary all
      - time zig build test --summary all
